# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Simsies
tagline:             'The blog of Josh Simmons'
description:         'An inside look at my creative process.'
url:                 https://simsi.es/blog
baseurl:             /blog
paginate:            5

# About/contact
author:
  name:              Josh Simmons
  url:               https://simsi.es/
  email:             jcpsimmons@gmail.com

# Custom vars
version:             1.0.0
