# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Simsies
tagline:          'Josh Simmons' Blog'
description:      'A process oriented look at my creative multimedia work.'
url:              http://simsi.es/
baseurl:          http://simsi.es/blog/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
