# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Simsies
tagline:          'The creative blog of Josh Simmons.'
description:      'An inside look at the multimedia works I'm creating, and how I'm creating them.'
url:              https://simsi.es/
baseurl:          https://simsi.es/blog/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
