baseurl = "/"
title = "Dr. Josh Simmons | Blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Dr. Josh Simmons"
    description = ""
    github = "https://github.com/jcpsimmons"
    email = "jcpsimmons@example.com"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"